# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: go-app
    metrics_path: /
    scheme: http
    scrape_interval: 10s
    static_configs:
      - targets:
        - 172.26.232.6:8080
        labels:
          group: 'applications'
          
  - job_name: prometheus
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: 
        - 172.26.232.6:9090
        
  - job_name: promgateway
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: 
        - 172.26.232.6:9091