# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093


# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: go-app
    metrics_path: /
    scheme: http
    scrape_interval: 10s
    static_configs:
      - targets:
        - ${IP_HOST}:8080
        labels:
          group: 'applications'
          
  - job_name: prometheus
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: 
        - ${IP_HOST}:9090
        - ${IP_HOST}:9115
        
  - job_name: promgateway
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: 
        - ${IP_HOST}:9091
        
  - job_name: blackbox
    metrics_path: /probe
    params:
        module: [http_2xx]
    static_configs:
        - targets:
            - ${IP_HOST}:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ${IP_HOST}:9115  